project:
  type: book

book:
  title: "Cookbook Data Analysis with Stata and R"
  author: "Manuel Oliveira"
  date: "2024"
  chapters:
    - index.qmd
    - intro.qmd
    - getting_started.qmd
    - ttest.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

